// AUTO-GENERATED by scripts/build-docs-index.ts. Do not edit by hand.
// Re-run `pnpm run build:docs` to regenerate.

export type MethodEntry = {
	kind: "method";
	name: string;
	qualified: string;
	description: string;
	params: unknown;
	exampleCall: string;
};

export type ProseEntry = {
	kind: "prose";
	id: string;
	title: string;
	content: string;
};

export type IndexEntry = MethodEntry | ProseEntry;

export const ENTRIES: IndexEntry[] = [
	{
		kind: "method",
		name: "defillama_get_chains",
		qualified: "defillama.protocol.getChains",
		description:
			"List every chain DefiLlama tracks, each with its current TVL. Returns the full array (sort/slice in your execute() script). The chain display names here (e.g. 'Ethereum', 'Arbitrum') feed api.llama.fi endpoints; lowercase the slug (e.g. 'ethereum') for coins.llama.fi price/block calls.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.protocol.getChains()",
	},
	{
		kind: "method",
		name: "defillama_get_protocols",
		qualified: "defillama.protocol.getProtocols",
		description:
			"List every DeFi protocol DefiLlama tracks with its TVL, category, chains and recent change metrics. Returns the full unsorted array (sort/slice/field-pick in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.protocol.getProtocols()",
	},
	{
		kind: "method",
		name: "defillama_get_protocol",
		qualified: "defillama.protocol.getProtocol",
		description:
			"Fetch detailed TVL data for a single DeFi protocol, including per-chain TVL breakdowns and historical series. Pass the protocol slug (e.g. 'lido', 'aave-v3'); resolve human-friendly names to slugs with the resolver/catalog before calling.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"Protocol slug as used by DefiLlama (e.g. 'lido', 'uniswap', 'aave-v3', 'makerdao'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall: "await defillama.protocol.getProtocol({protocol: 'lido'})",
	},
	{
		kind: "method",
		name: "defillama_get_historical_chain_tvl",
		qualified: "defillama.protocol.getHistoricalChainTvl",
		description:
			"Fetch the historical TVL time series for a chain, or aggregated across all chains when `chain` is omitted. Returns the full series (slice the tail in your execute() script). Use the chain display name from getChains() (e.g. 'Ethereum'), which feeds the api.llama.fi endpoint.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'Arbitrum', 'Polygon'). If omitted, returns aggregated historical TVL across all chains combined.",
					type: "string",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.protocol.getHistoricalChainTvl({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_dex_summary",
		qualified: "defillama.dex.getDexSummary",
		description:
			"Fetch detailed DEX trading-volume data for a single protocol, including totals and (optionally) the volume chart series. Pass the protocol slug; resolve display names to slugs via the catalog first.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"DEX protocol slug (e.g. 'uniswap', 'pancakeswap', 'curve-dex'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated volume chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-chain chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall: "await defillama.dex.getDexSummary({protocol: 'uniswap'})",
	},
	{
		kind: "method",
		name: "defillama_get_dexs_overview",
		qualified: "defillama.dex.getDexsOverview",
		description:
			"Fetch a DEX volume overview across all DEXs, or scoped to one chain when `chain` is provided. Returns the full `protocols` array (sort/slice/field-pick in your execute() script). Use the chain display name (e.g. 'Ethereum').",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'BSC', 'Arbitrum'). If omitted, returns the global overview of all DEXs.",
					type: "string",
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated volume chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-protocol chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall: "await defillama.dex.getDexsOverview({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_fees_summary",
		qualified: "defillama.fees.getFeesSummary",
		description:
			"Fetch detailed fees/revenue metrics for a single protocol. Pass the protocol slug; resolve display names to slugs via the catalog first. Use `dataType` to choose which metric series to return.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"Protocol slug (e.g. 'uniswap', 'aave'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
				dataType: {
					description:
						"Which metric to retrieve: 'dailyFees', 'dailyRevenue', or 'dailyHoldersRevenue'.",
					type: "string",
					enum: ["dailyFees", "dailyRevenue", "dailyHoldersRevenue"],
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-chain chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.fees.getFeesSummary({protocol: 'uniswap', dataType: 'dailyRevenue'})",
	},
	{
		kind: "method",
		name: "defillama_get_fees_overview",
		qualified: "defillama.fees.getFeesOverview",
		description:
			"Fetch a fees/revenue overview across all protocols, or scoped to one chain when `chain` is provided. Returns the full `protocols` array (sort/slice/field-pick in your execute() script). Use the chain display name (e.g. 'Ethereum').",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'Polygon', 'BSC'). If omitted, includes all chains.",
					type: "string",
				},
				dataType: {
					description:
						"Which metric to retrieve: 'dailyFees', 'dailyRevenue', or 'dailyHoldersRevenue'.",
					type: "string",
					enum: ["dailyFees", "dailyRevenue", "dailyHoldersRevenue"],
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-protocol chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.fees.getFeesOverview({chain: 'Ethereum', dataType: 'dailyFees'})",
	},
	{
		kind: "method",
		name: "defillama_get_options_summary",
		qualified: "defillama.options.getOptionsSummary",
		description:
			"Fetch detailed options-protocol volume data for a single protocol. Pass the protocol slug; resolve display names to slugs via the catalog first. Use `dataType` to choose premium vs notional volume.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"Options protocol slug (e.g. 'lyra', 'hegic', 'aevo'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
				dataType: {
					description:
						"Which volume to retrieve: 'dailyPremiumVolume' (premiums paid) or 'dailyNotionalVolume' (value of underlying assets).",
					type: "string",
					enum: ["dailyPremiumVolume", "dailyNotionalVolume"],
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.options.getOptionsSummary({protocol: 'lyra'})",
	},
	{
		kind: "method",
		name: "defillama_get_options_overview",
		qualified: "defillama.options.getOptionsOverview",
		description:
			"Fetch an options-volume overview across all options protocols, or scoped to one chain when `chain` is provided. Returns the full `protocols` array (sort/slice in your execute() script). Use the chain display name (e.g. 'Ethereum').",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'Arbitrum', 'Optimism'). If omitted, returns the global overview of all options protocols.",
					type: "string",
				},
				dataType: {
					description:
						"Which volume to retrieve: 'dailyPremiumVolume' (premiums paid) or 'dailyNotionalVolume' (value of underlying assets).",
					type: "string",
					enum: ["dailyPremiumVolume", "dailyNotionalVolume"],
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-protocol chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.options.getOptionsOverview({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin",
		qualified: "defillama.stablecoin.getStablecoins",
		description:
			"List all stablecoins with circulation data (and optionally current prices). Returns the full `peggedAssets` array (sort/slice/field-pick in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				includePrices: {
					description: "Include current price data for each stablecoin.",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.stablecoin.getStablecoins({includePrices: true})",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin_chains",
		qualified: "defillama.stablecoin.getStablecoinChains",
		description:
			"List stablecoin market-cap totals broken down by chain. Returns the full array (slice/sort in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.stablecoin.getStablecoinChains()",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin_charts",
		qualified: "defillama.stablecoin.getStablecoinCharts",
		description:
			"Fetch the historical stablecoin market-cap chart, optionally scoped to a chain and/or a single stablecoin. Returns the full series (slice the tail in your execute() script). Use the chain display name (e.g. 'Ethereum'); omit `chain` for global aggregated data.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name to filter by (e.g. 'Ethereum', 'Polygon'). If omitted, returns global aggregated data across all chains.",
					type: "string",
				},
				stablecoin: {
					description:
						"Stablecoin numeric ID (e.g. 1 for USDT) to filter to a single asset. Resolve symbols/names to IDs deterministically via the catalog before calling.",
					anyOf: [
						{
							type: "integer",
							minimum: -9007199254740991,
							maximum: 9007199254740991,
						},
						{
							type: "string",
						},
					],
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.stablecoin.getStablecoinCharts({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin_prices",
		qualified: "defillama.stablecoin.getStablecoinPrices",
		description:
			"Fetch the historical stablecoin price series (per-asset prices over time). Returns the full series (slice the tail in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.stablecoin.getStablecoinPrices()",
	},
	{
		kind: "method",
		name: "defillama_get_prices_current_coins",
		qualified: "defillama.price.getCurrentPrices",
		description:
			"Fetch current token prices. Tokens are identified in the format `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7'). Comma-separate multiple tokens. CoinGecko IDs use the 'coingecko:<id>' prefix.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...'), or 'coingecko:<id>' for well-known coins.",
					type: "string",
				},
				searchWidth: {
					description:
						"Time window to search for price data: a duration string (e.g. '4h', '1d', '30m') or seconds as a number (e.g. 600).",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getCurrentPrices({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7'})",
	},
	{
		kind: "method",
		name: "defillama_get_prices_first_coins",
		qualified: "defillama.price.getFirstPrices",
		description:
			"Fetch the first-ever recorded price for each token. Tokens are identified in the format `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'). Comma-separate multiple tokens. Useful for when a token was first listed/tracked.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...').",
					type: "string",
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getFirstPrices({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7'})",
	},
	{
		kind: "method",
		name: "defillama_get_batch_historical",
		qualified: "defillama.price.getBatchHistorical",
		description:
			"Fetch historical prices for many tokens at many timestamps in one call. `coins` is an object mapping `{chain}:{address}` (lowercase chain slug) to an array of Unix timestamps in seconds. A pre-encoded string is also accepted.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Object mapping `{chain}:{address}` (lowercase chain slug) to an array of Unix timestamps in seconds, e.g. { 'ethereum:0xdac1...': [1648680149] } or { 'coingecko:bitcoin': [1648680149, 1648766549] }. A pre-encoded string is also accepted.",
					anyOf: [
						{
							type: "string",
							minLength: 1,
						},
						{
							type: "object",
							propertyNames: {
								type: "string",
							},
							additionalProperties: {
								minItems: 1,
								type: "array",
								items: {
									anyOf: [
										{
											type: "integer",
											minimum: 0,
											maximum: 9007199254740991,
										},
										{
											type: "string",
											minLength: 1,
										},
									],
								},
							},
						},
					],
				},
				searchWidth: {
					description:
						"Time window around each timestamp: a duration string (e.g. '6h', '1d') or seconds as a number (e.g. 600).",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getBatchHistorical({coins: {'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7': [1648680149]}})",
	},
	{
		kind: "method",
		name: "defillama_get_historical_prices_by_contract",
		qualified: "defillama.price.getHistoricalPrices",
		description:
			"Fetch token prices at a single point in time. Tokens are identified in the format `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'). Comma-separate multiple tokens. `timestamp` accepts Unix seconds or an ISO 8601 date string.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...').",
					type: "string",
				},
				timestamp: {
					description:
						"Point in time to query. Unix timestamp in seconds (e.g. 1705320000) or ISO 8601 (e.g. '2024-01-15T12:00:00Z').",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
				searchWidth: {
					description:
						"Time window around the timestamp: a duration string (e.g. '6h', '1d') or seconds as a number.",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins", "timestamp"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getHistoricalPrices({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7', timestamp: 1705320000})",
	},
	{
		kind: "method",
		name: "defillama_get_percentage_coins",
		qualified: "defillama.price.getPercentageChange",
		description:
			"Fetch the percentage price change for tokens over a period, looking backward (default) or forward. Tokens are `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'). Comma-separate multiple tokens.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...').",
					type: "string",
				},
				period: {
					description:
						"Period over which to compute the change. Format number+unit (h=hours, d=days), e.g. '1h', '7d'. Defaults to '1d'.",
					type: "string",
				},
				lookForward: {
					description:
						"If false (default) compute change from [timestamp - period] to [timestamp]; if true, from [timestamp] to [timestamp + period].",
					type: "boolean",
				},
				timestamp: {
					description:
						"Starting point for the calculation. Unix seconds or ISO 8601. If omitted, uses the current time.",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getPercentageChange({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7', period: '7d'})",
	},
	{
		kind: "method",
		name: "defillama_get_chart_coins",
		qualified: "defillama.price.getPriceChart",
		description:
			"Fetch a historical price chart (time series) for one or more tokens. Tokens are `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'); CoinGecko IDs use 'coingecko:<id>'. Control the range and granularity with start/end/span/period.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...'), or 'coingecko:<id>'.",
					type: "string",
				},
				start: {
					description:
						"Unix timestamp (seconds) of the earliest data point. If omitted, uses the earliest available data.",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
				end: {
					description:
						"Unix timestamp (seconds) of the latest data point. If omitted, uses the current time.",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
				span: {
					description:
						"Number of evenly-spaced data points to return. If omitted, returns all available points in range.",
					type: "integer",
					minimum: 0,
					maximum: 9007199254740991,
				},
				period: {
					description:
						"Interval between data points. Format number+unit (h=hours, d=days), e.g. '1h', '1d'. Defaults to daily.",
					type: "string",
				},
				searchWidth: {
					description:
						"Time window for finding price data around each period point: seconds (number) or a duration string.",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getPriceChart({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7', span: 10, period: '1d'})",
	},
	{
		kind: "method",
		name: "defillama_get_latest_pool_data",
		qualified: "defillama.yield.getLatestPools",
		description:
			"List current yield-farming pools with APY, TVL and reward metrics. Returns the full `data` array (sort/slice/field-pick in your execute() script). Each pool's `pool` UUID feeds getHistoricalPoolData.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.yield.getLatestPools()",
	},
	{
		kind: "method",
		name: "defillama_get_historical_pool_data",
		qualified: "defillama.yield.getHistoricalPoolData",
		description:
			"Fetch the historical APY/TVL series for a single yield pool. Returns the full series (slice the tail in your execute() script). Get the pool UUID from getLatestPools first.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				pool: {
					description:
						"Pool UUID as returned in the `pool` field of getLatestPools (e.g. '747c1d2a-c668-4682-b9f9-296708a3dd90').",
					type: "string",
				},
			},
			required: ["pool"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.yield.getHistoricalPoolData({pool: '747c1d2a-c668-4682-b9f9-296708a3dd90'})",
	},
	{
		kind: "method",
		name: "defillama_get_blockchain_timestamp",
		qualified: "defillama.blockchain.getBlockAtTimestamp",
		description:
			"Resolve the block (height + timestamp) closest to a given time on a chain. Essential for historical queries that need a block number. Use the lowercase chain slug (e.g. 'ethereum') for this coins.llama.fi endpoint. `timestamp` accepts Unix seconds or an ISO 8601 date string.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Lowercase chain slug for the coins.llama.fi endpoint (e.g. 'ethereum', 'polygon', 'arbitrum').",
					type: "string",
				},
				timestamp: {
					description:
						"Time to query. Unix timestamp in seconds (e.g. 1640000000) or ISO 8601 date string (e.g. '2024-01-15T10:30:00Z').",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
			},
			required: ["chain", "timestamp"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.blockchain.getBlockAtTimestamp({chain: 'ethereum', timestamp: 1640000000})",
	},
];
