// AUTO-GENERATED by scripts/build-docs-index.ts. Do not edit by hand.
// Re-run `pnpm run build:docs` to regenerate.

export type MethodEntry = {
	kind: "method";
	name: string;
	qualified: string;
	description: string;
	params: unknown;
	exampleCall: string;
};

export type ProseEntry = {
	kind: "prose";
	id: string;
	title: string;
	content: string;
};

export type IndexEntry = MethodEntry | ProseEntry;

export const ENTRIES: IndexEntry[] = [
	{
		kind: "method",
		name: "defillama_get_chains",
		qualified: "defillama.protocol.getChains",
		description:
			"List every chain DefiLlama tracks, each with its current TVL. Returns the full array (sort/slice in your execute() script). The chain display names here (e.g. 'Ethereum', 'Arbitrum') feed api.llama.fi endpoints; lowercase the slug (e.g. 'ethereum') for coins.llama.fi price/block calls.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.protocol.getChains()",
	},
	{
		kind: "method",
		name: "defillama_get_protocols",
		qualified: "defillama.protocol.getProtocols",
		description:
			"List every DeFi protocol DefiLlama tracks with its TVL, category, chains and recent change metrics. Returns the full unsorted array (sort/slice/field-pick in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.protocol.getProtocols()",
	},
	{
		kind: "method",
		name: "defillama_get_protocol",
		qualified: "defillama.protocol.getProtocol",
		description:
			"Fetch detailed TVL data for a single DeFi protocol, including per-chain TVL breakdowns and historical series. Pass the protocol slug (e.g. 'lido', 'aave-v3'); resolve human-friendly names to slugs with the resolver/catalog before calling.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"Protocol slug as used by DefiLlama (e.g. 'lido', 'uniswap', 'aave-v3', 'makerdao'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall: "await defillama.protocol.getProtocol({protocol: 'lido'})",
	},
	{
		kind: "method",
		name: "defillama_get_historical_chain_tvl",
		qualified: "defillama.protocol.getHistoricalChainTvl",
		description:
			"Fetch the historical TVL time series for a chain, or aggregated across all chains when `chain` is omitted. Returns the full series (slice the tail in your execute() script). Use the chain display name from getChains() (e.g. 'Ethereum'), which feeds the api.llama.fi endpoint.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'Arbitrum', 'Polygon'). If omitted, returns aggregated historical TVL across all chains combined.",
					type: "string",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.protocol.getHistoricalChainTvl({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_dex_summary",
		qualified: "defillama.dex.getDexSummary",
		description:
			"Fetch detailed DEX trading-volume data for a single protocol, including totals and (optionally) the volume chart series. Pass the protocol slug; resolve display names to slugs via the catalog first.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"DEX protocol slug (e.g. 'uniswap', 'pancakeswap', 'curve-dex'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated volume chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-chain chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall: "await defillama.dex.getDexSummary({protocol: 'uniswap'})",
	},
	{
		kind: "method",
		name: "defillama_get_dexs_overview",
		qualified: "defillama.dex.getDexsOverview",
		description:
			"Fetch a DEX volume overview across all DEXs, or scoped to one chain when `chain` is provided. Returns the full `protocols` array (sort/slice/field-pick in your execute() script). Use the chain display name (e.g. 'Ethereum').",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'BSC', 'Arbitrum'). If omitted, returns the global overview of all DEXs.",
					type: "string",
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated volume chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-protocol chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall: "await defillama.dex.getDexsOverview({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_fees_summary",
		qualified: "defillama.fees.getFeesSummary",
		description:
			"Fetch detailed fees/revenue metrics for a single protocol. Pass the protocol slug; resolve display names to slugs via the catalog first. Use `dataType` to choose which metric series to return.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"Protocol slug (e.g. 'uniswap', 'aave'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
				dataType: {
					description:
						"Which metric to retrieve: 'dailyFees', 'dailyRevenue', or 'dailyHoldersRevenue'.",
					type: "string",
					enum: ["dailyFees", "dailyRevenue", "dailyHoldersRevenue"],
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-chain chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.fees.getFeesSummary({protocol: 'uniswap', dataType: 'dailyRevenue'})",
	},
	{
		kind: "method",
		name: "defillama_get_fees_overview",
		qualified: "defillama.fees.getFeesOverview",
		description:
			"Fetch a fees/revenue overview across all protocols, or scoped to one chain when `chain` is provided. Returns the full `protocols` array (sort/slice/field-pick in your execute() script). Use the chain display name (e.g. 'Ethereum').",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'Polygon', 'BSC'). If omitted, includes all chains.",
					type: "string",
				},
				dataType: {
					description:
						"Which metric to retrieve: 'dailyFees', 'dailyRevenue', or 'dailyHoldersRevenue'.",
					type: "string",
					enum: ["dailyFees", "dailyRevenue", "dailyHoldersRevenue"],
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-protocol chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.fees.getFeesOverview({chain: 'Ethereum', dataType: 'dailyFees'})",
	},
	{
		kind: "method",
		name: "defillama_get_options_summary",
		qualified: "defillama.options.getOptionsSummary",
		description:
			"Fetch detailed options-protocol volume data for a single protocol. Pass the protocol slug; resolve display names to slugs via the catalog first. Use `dataType` to choose premium vs notional volume.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol: {
					description:
						"Options protocol slug (e.g. 'lyra', 'hegic', 'aevo'). Resolve display names to slugs deterministically via the catalog before calling.",
					type: "string",
				},
				dataType: {
					description:
						"Which volume to retrieve: 'dailyPremiumVolume' (premiums paid) or 'dailyNotionalVolume' (value of underlying assets).",
					type: "string",
					enum: ["dailyPremiumVolume", "dailyNotionalVolume"],
				},
			},
			required: ["protocol"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.options.getOptionsSummary({protocol: 'lyra'})",
	},
	{
		kind: "method",
		name: "defillama_get_options_overview",
		qualified: "defillama.options.getOptionsOverview",
		description:
			"Fetch an options-volume overview across all options protocols, or scoped to one chain when `chain` is provided. Returns the full `protocols` array (sort/slice in your execute() script). Use the chain display name (e.g. 'Ethereum').",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name (e.g. 'Ethereum', 'Arbitrum', 'Optimism'). If omitted, returns the global overview of all options protocols.",
					type: "string",
				},
				dataType: {
					description:
						"Which volume to retrieve: 'dailyPremiumVolume' (premiums paid) or 'dailyNotionalVolume' (value of underlying assets).",
					type: "string",
					enum: ["dailyPremiumVolume", "dailyNotionalVolume"],
				},
				excludeTotalDataChart: {
					description:
						"Exclude the aggregated chart series from the response (defaults to true upstream).",
					type: "boolean",
				},
				excludeTotalDataChartBreakdown: {
					description:
						"Exclude the per-protocol chart breakdown from the response (defaults to true upstream).",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.options.getOptionsOverview({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin",
		qualified: "defillama.stablecoin.getStablecoins",
		description:
			"List all stablecoins with circulation data (and optionally current prices). Returns the full `peggedAssets` array (sort/slice/field-pick in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				includePrices: {
					description: "Include current price data for each stablecoin.",
					type: "boolean",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.stablecoin.getStablecoins({includePrices: true})",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin_chains",
		qualified: "defillama.stablecoin.getStablecoinChains",
		description:
			"List stablecoin market-cap totals broken down by chain. Returns the full array (slice/sort in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.stablecoin.getStablecoinChains()",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin_charts",
		qualified: "defillama.stablecoin.getStablecoinCharts",
		description:
			"Fetch the historical stablecoin market-cap chart, optionally scoped to a chain and/or a single stablecoin. Returns the full series (slice the tail in your execute() script). Use the chain display name (e.g. 'Ethereum'); omit `chain` for global aggregated data.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Chain display name to filter by (e.g. 'Ethereum', 'Polygon'). If omitted, returns global aggregated data across all chains.",
					type: "string",
				},
				stablecoin: {
					description:
						"Stablecoin numeric ID (e.g. 1 for USDT) to filter to a single asset. Resolve symbols/names to IDs deterministically via the catalog before calling.",
					anyOf: [
						{
							type: "integer",
							minimum: -9007199254740991,
							maximum: 9007199254740991,
						},
						{
							type: "string",
						},
					],
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.stablecoin.getStablecoinCharts({chain: 'Ethereum'})",
	},
	{
		kind: "method",
		name: "defillama_get_stablecoin_prices",
		qualified: "defillama.stablecoin.getStablecoinPrices",
		description:
			"Fetch the historical stablecoin price series (per-asset prices over time). Returns the full series (slice the tail in your execute() script).",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.stablecoin.getStablecoinPrices()",
	},
	{
		kind: "method",
		name: "defillama_get_prices_current_coins",
		qualified: "defillama.price.getCurrentPrices",
		description:
			"Fetch current token prices. Tokens are identified in the format `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7'). Comma-separate multiple tokens. CoinGecko IDs use the 'coingecko:<id>' prefix.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...'), or 'coingecko:<id>' for well-known coins.",
					type: "string",
				},
				searchWidth: {
					description:
						"Time window to search for price data: a duration string (e.g. '4h', '1d', '30m') or seconds as a number (e.g. 600).",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getCurrentPrices({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7'})",
	},
	{
		kind: "method",
		name: "defillama_get_prices_first_coins",
		qualified: "defillama.price.getFirstPrices",
		description:
			"Fetch the first-ever recorded price for each token. Tokens are identified in the format `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'). Comma-separate multiple tokens. Useful for when a token was first listed/tracked.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...').",
					type: "string",
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getFirstPrices({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7'})",
	},
	{
		kind: "method",
		name: "defillama_get_batch_historical",
		qualified: "defillama.price.getBatchHistorical",
		description:
			"Fetch historical prices for many tokens at many timestamps in one call. `coins` is an object mapping `{chain}:{address}` (lowercase chain slug) to an array of Unix timestamps in seconds. A pre-encoded string is also accepted.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Object mapping `{chain}:{address}` (lowercase chain slug) to an array of Unix timestamps in seconds, e.g. { 'ethereum:0xdac1...': [1648680149] } or { 'coingecko:bitcoin': [1648680149, 1648766549] }. A pre-encoded string is also accepted.",
					anyOf: [
						{
							type: "string",
							minLength: 1,
						},
						{
							type: "object",
							propertyNames: {
								type: "string",
							},
							additionalProperties: {
								minItems: 1,
								type: "array",
								items: {
									anyOf: [
										{
											type: "integer",
											minimum: 0,
											maximum: 9007199254740991,
										},
										{
											type: "string",
											minLength: 1,
										},
									],
								},
							},
						},
					],
				},
				searchWidth: {
					description:
						"Time window around each timestamp: a duration string (e.g. '6h', '1d') or seconds as a number (e.g. 600).",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getBatchHistorical({coins: {'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7': [1648680149]}})",
	},
	{
		kind: "method",
		name: "defillama_get_historical_prices_by_contract",
		qualified: "defillama.price.getHistoricalPrices",
		description:
			"Fetch token prices at a single point in time. Tokens are identified in the format `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'). Comma-separate multiple tokens. `timestamp` accepts Unix seconds or an ISO 8601 date string.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...').",
					type: "string",
				},
				timestamp: {
					description:
						"Point in time to query. Unix timestamp in seconds (e.g. 1705320000) or ISO 8601 (e.g. '2024-01-15T12:00:00Z').",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
				searchWidth: {
					description:
						"Time window around the timestamp: a duration string (e.g. '6h', '1d') or seconds as a number.",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins", "timestamp"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getHistoricalPrices({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7', timestamp: 1705320000})",
	},
	{
		kind: "method",
		name: "defillama_get_percentage_coins",
		qualified: "defillama.price.getPercentageChange",
		description:
			"Fetch the percentage price change for tokens over a period, looking backward (default) or forward. Tokens are `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'). Comma-separate multiple tokens.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...').",
					type: "string",
				},
				period: {
					description:
						"Period over which to compute the change. Format number+unit (h=hours, d=days), e.g. '1h', '7d'. Defaults to '1d'.",
					type: "string",
				},
				lookForward: {
					description:
						"If false (default) compute change from [timestamp - period] to [timestamp]; if true, from [timestamp] to [timestamp + period].",
					type: "boolean",
				},
				timestamp: {
					description:
						"Starting point for the calculation. Unix seconds or ISO 8601. If omitted, uses the current time.",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getPercentageChange({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7', period: '7d'})",
	},
	{
		kind: "method",
		name: "defillama_get_chart_coins",
		qualified: "defillama.price.getPriceChart",
		description:
			"Fetch a historical price chart (time series) for one or more tokens. Tokens are `{chain}:{address}` with a lowercase chain slug (e.g. 'ethereum:0xdac1...'); CoinGecko IDs use 'coingecko:<id>'. Control the range and granularity with start/end/span/period.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				coins: {
					description:
						"Comma-separated tokens in `{chain}:{address}` format with a lowercase chain slug (e.g. 'ethereum:0xdac1...,bsc:0x55d3...'), or 'coingecko:<id>'.",
					type: "string",
				},
				start: {
					description:
						"Unix timestamp (seconds) of the earliest data point. If omitted, uses the earliest available data.",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
				end: {
					description:
						"Unix timestamp (seconds) of the latest data point. If omitted, uses the current time.",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
				span: {
					description:
						"Number of evenly-spaced data points to return. If omitted, returns all available points in range.",
					type: "integer",
					minimum: 0,
					maximum: 9007199254740991,
				},
				period: {
					description:
						"Interval between data points. Format number+unit (h=hours, d=days), e.g. '1h', '1d'. Defaults to daily.",
					type: "string",
				},
				searchWidth: {
					description:
						"Time window for finding price data around each period point: seconds (number) or a duration string.",
					anyOf: [
						{
							type: "string",
						},
						{
							type: "number",
						},
					],
				},
			},
			required: ["coins"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.price.getPriceChart({coins: 'ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7', span: 10, period: '1d'})",
	},
	{
		kind: "method",
		name: "defillama_get_latest_pool_data",
		qualified: "defillama.yield.getLatestPools",
		description:
			"List current yield-farming pools with APY, TVL and reward metrics. Returns the full `data` array (sort/slice/field-pick in your execute() script). Each pool's `pool` UUID feeds getHistoricalPoolData.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await defillama.yield.getLatestPools()",
	},
	{
		kind: "method",
		name: "defillama_get_historical_pool_data",
		qualified: "defillama.yield.getHistoricalPoolData",
		description:
			"Fetch the historical APY/TVL series for a single yield pool. Returns the full series (slice the tail in your execute() script). Get the pool UUID from getLatestPools first.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				pool: {
					description:
						"Pool UUID as returned in the `pool` field of getLatestPools (e.g. '747c1d2a-c668-4682-b9f9-296708a3dd90').",
					type: "string",
				},
			},
			required: ["pool"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.yield.getHistoricalPoolData({pool: '747c1d2a-c668-4682-b9f9-296708a3dd90'})",
	},
	{
		kind: "method",
		name: "defillama_get_blockchain_timestamp",
		qualified: "defillama.blockchain.getBlockAtTimestamp",
		description:
			"Resolve the block (height + timestamp) closest to a given time on a chain. Essential for historical queries that need a block number. Use the lowercase chain slug (e.g. 'ethereum') for this coins.llama.fi endpoint. `timestamp` accepts Unix seconds or an ISO 8601 date string.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain: {
					description:
						"Lowercase chain slug for the coins.llama.fi endpoint (e.g. 'ethereum', 'polygon', 'arbitrum').",
					type: "string",
				},
				timestamp: {
					description:
						"Time to query. Unix timestamp in seconds (e.g. 1640000000) or ISO 8601 date string (e.g. '2024-01-15T10:30:00Z').",
					anyOf: [
						{
							type: "integer",
							minimum: 0,
							maximum: 9007199254740991,
						},
						{
							type: "string",
							minLength: 1,
						},
					],
				},
			},
			required: ["chain", "timestamp"],
			additionalProperties: false,
		},
		exampleCall:
			"await defillama.blockchain.getBlockAtTimestamp({chain: 'ethereum', timestamp: 1640000000})",
	},
	{
		kind: "prose",
		id: "cookbook:01-top-protocols-by-tvl.md",
		title: "Rank the top protocols by TVL",
		content:
			"# Rank the top protocols by TVL\n\nFetches every protocol DefiLlama tracks and returns the ten largest by current TVL, with the chains each protocol is deployed on. `getProtocols()` returns the full unsorted array, so the sort/slice/projection happens in your `execute()` script — only the small projected result crosses the sandbox boundary.\n\n```js\nasync function run(defillama) {\n  const protocols = await defillama.protocol.getProtocols();\n  return protocols\n    .sort((a, b) => (b.tvl ?? 0) - (a.tvl ?? 0))\n    .slice(0, 10)\n    .map((p) => ({ name: p.name, tvl: p.tvl, chains: p.chains }));\n}\n```\n",
	},
	{
		kind: "prose",
		id: "cookbook:02-dex-volume-leaderboard.md",
		title: "DEX volume leaderboard for a chain",
		content:
			'# DEX volume leaderboard for a chain\n\nBuilds a leaderboard of the highest-volume DEXs on a single chain using 24h volume. `getDexsOverview` expects the chain **display name** (e.g. `\'Ethereum\'`) for api.llama.fi — use `defillama.resolveChain(...).name` to turn a user alias like "eth" into the correct display name first. The DEX rows live under `.protocols`.\n\n```js\nasync function run(defillama) {\n  const chain = await defillama.resolveChain("Ethereum"); // {name, slug}\n  const overview = await defillama.dex.getDexsOverview({ chain: chain.name });\n  return (overview.protocols ?? [])\n    .sort((a, b) => (b.total24h ?? 0) - (a.total24h ?? 0))\n    .slice(0, 10)\n    .map((d) => ({ name: d.name, volume24h: d.total24h }));\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:03-fees-vs-revenue.md",
		title: "Compare protocol fees vs revenue",
		content:
			"# Compare protocol fees vs revenue\n\nJoins each protocol's 24h fees against its 24h revenue to surface where fees translate into protocol revenue. Call `getFeesOverview` twice — once with `dataType: 'dailyFees'` and once with `dataType: 'dailyRevenue'` — then join the two `.protocols` arrays by name.\n\n```js\nasync function run(defillama) {\n  const feesOv = await defillama.fees.getFeesOverview({ dataType: \"dailyFees\" });\n  const revOv = await defillama.fees.getFeesOverview({ dataType: \"dailyRevenue\" });\n\n  const revByName = new Map(\n    (revOv.protocols ?? []).map((p) => [p.name, p.total24h ?? 0]),\n  );\n\n  return (feesOv.protocols ?? [])\n    .map((p) => ({\n      name: p.name,\n      fees24h: p.total24h ?? 0,\n      revenue24h: revByName.get(p.name) ?? 0,\n    }))\n    .sort((a, b) => b.fees24h - a.fees24h)\n    .slice(0, 10);\n}\n```\n",
	},
	{
		kind: "prose",
		id: "cookbook:04-stablecoin-mcap-by-chain.md",
		title: "Stablecoin market cap by chain",
		content:
			"# Stablecoin market cap by chain\n\nReturns total stablecoin circulating market cap broken down per chain, sorted largest first. `getStablecoinChains()` returns one row per chain; the USD total lives under `totalCirculatingUSD.peggedUSD`.\n\n```js\nasync function run(defillama) {\n  const chains = await defillama.stablecoin.getStablecoinChains();\n  return chains\n    .map((c) => ({\n      chain: c.name,\n      circulatingUsd: c.totalCirculatingUSD?.peggedUSD ?? 0,\n    }))\n    .sort((a, b) => b.circulatingUsd - a.circulatingUsd);\n}\n```\n",
	},
	{
		kind: "prose",
		id: "cookbook:05-token-price-history.md",
		title: "Token price history via chain:address",
		content:
			'# Token price history via chain:address\n\nFetches a historical price chart for a token. The coins API identifies tokens as `{chainSlug}:{address}` with a **lowercase** chain slug — use `defillama.resolveChain(...).slug` to build the key (the `.slug` form feeds coins.llama.fi, not the `.name` form). `getPriceChart` returns a series keyed by the same coins identifier under `.coins[key].prices`.\n\n```js\nasync function run(defillama) {\n  const chain = await defillama.resolveChain("Ethereum"); // {name, slug:"ethereum"}\n  const key = chain.slug + ":0xdac17f958d2ee523a2206206994597c13d831ec7"; // USDT\n  const chart = await defillama.price.getPriceChart({\n    coins: key,\n    span: 30,\n    period: "1d",\n  });\n  const series = chart.coins?.[key]?.prices ?? [];\n  return { coin: key, points: series.length, prices: series };\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:06-block-at-timestamp-tvl.md",
		title: "Correlate a block at a timestamp with historical chain TVL",
		content:
			'# Correlate a block at a timestamp with historical chain TVL\n\nResolves the block closest to a given timestamp, then pulls the historical TVL series for the same chain so you can correlate on-chain state with TVL. Note the two host conventions: `getBlockAtTimestamp` is a coins.llama.fi call and wants the **lowercase slug** (`chain.slug`), while `getHistoricalChainTvl` is an api.llama.fi call and wants the **display name** (`chain.name`).\n\n```js\nasync function run(defillama) {\n  const chain = await defillama.resolveChain("Ethereum"); // {name:"Ethereum", slug:"ethereum"}\n  const timestamp = 1700000000;\n\n  const block = await defillama.blockchain.getBlockAtTimestamp({\n    chain: chain.slug,\n    timestamp,\n  });\n  const tvl = await defillama.protocol.getHistoricalChainTvl({\n    chain: chain.name,\n  });\n\n  return {\n    height: block.height,\n    blockTimestamp: block.timestamp,\n    tvlPoints: tvl.length,\n    latestTvl: tvl[tvl.length - 1],\n  };\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:07-yield-pool-screen.md",
		title: "Screen yield pools, then drill into one",
		content:
			"# Screen yield pools, then drill into one\n\nFilters the full yield-pool universe by minimum TVL and APY, takes the top pools by APY, then fetches the historical APY/TVL series for the single best pool. `getLatestPools()` returns rows under `.data`; each row's `pool` UUID feeds `getHistoricalPoolData`.\n\n```js\nasync function run(defillama) {\n  const { data } = await defillama.yield.getLatestPools();\n  const screened = data\n    .filter((p) => (p.tvlUsd ?? 0) >= 1_000_000 && (p.apy ?? 0) >= 5)\n    .sort((a, b) => (b.apy ?? 0) - (a.apy ?? 0))\n    .slice(0, 5)\n    .map((p) => ({\n      pool: p.pool,\n      project: p.project,\n      symbol: p.symbol,\n      chain: p.chain,\n      tvlUsd: p.tvlUsd,\n      apy: p.apy,\n    }));\n\n  const top = screened[0];\n  const history = top\n    ? await defillama.yield.getHistoricalPoolData({ pool: top.pool })\n    : null;\n\n  return { screened, topPoolHistory: history?.data?.slice(-30) };\n}\n```\n",
	},
	{
		kind: "prose",
		id: "cookbook:08-resolve-names.md",
		title: "Resolve chain, protocol, and stablecoin names",
		content:
			'# Resolve chain, protocol, and stablecoin names\n\nTranslates human-facing names into the exact identifiers each DefiLlama endpoint expects, deterministically (no LLM). The key convention: a chain resolves to BOTH a `name` and a `slug` — use `.name` for api.llama.fi group endpoints (protocols, dexs, fees, historical chain TVL) and `.slug` for coins.llama.fi calls (prices, block-at-timestamp). Protocols resolve to a slug string; stablecoins resolve to a numeric id string.\n\n```js\nasync function run(defillama) {\n  const chain = await defillama.resolveChain("BSC"); // {name:"BSC", slug:"bsc"}\n  const protocol = await defillama.resolveProtocol("Lido"); // "lido"\n  const stablecoin = await defillama.resolveStablecoin("USDC"); // e.g. "2"\n\n  // Use .name for api.llama.fi groups, .slug for coins/price endpoints.\n  return {\n    chainName: chain?.name, // -> getHistoricalChainTvl({chain: chain.name})\n    chainSlug: chain?.slug, // -> getBlockAtTimestamp({chain: chain.slug})\n    protocolSlug: protocol, // -> getProtocol({protocol})\n    stablecoinId: stablecoin, // -> getStablecoinCharts({stablecoin})\n  };\n}\n```\n',
	},
];
