export const chains = [
	{
		name: "Optimism",
		chainId: 10,
		gecko_id: "optimism",
		tokenSymbol: "OP",
	},
	{
		name: "Ethereum",
		chainId: 1,
		gecko_id: "ethereum",
		tokenSymbol: "ETH",
	},
	{
		name: "Arbitrum",
		chainId: 42161,
		gecko_id: "arbitrum",
		tokenSymbol: "ARB",
	},
	{
		name: "Base",
		chainId: 8453,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Fantom",
		chainId: 250,
		gecko_id: "fantom",
		tokenSymbol: "FTM",
	},
	{
		name: "Polygon",
		chainId: 137,
		gecko_id: "matic-network",
		tokenSymbol: "MATIC",
	},
	{
		name: "Moonriver",
		chainId: 1285,
		gecko_id: "moonriver",
		tokenSymbol: "MOVR",
	},
	{
		name: "BSC",
		chainId: 56,
		gecko_id: "binancecoin",
		tokenSymbol: "BNB",
	},
	{
		name: "Gnosis",
		chainId: 100,
		gecko_id: "gnosis",
		tokenSymbol: "GNO",
	},
	{
		name: "Heco",
		chainId: 128,
		gecko_id: "huobi-token",
		tokenSymbol: "HT",
	},
	{
		name: "Avalanche",
		chainId: 43114,
		gecko_id: "avalanche-2",
		tokenSymbol: "AVAX",
	},
	{
		name: "Telos",
		chainId: 40,
		gecko_id: "telos",
		tokenSymbol: "TLOS",
	},
	{
		name: "Celo",
		chainId: 42220,
		gecko_id: "celo",
		tokenSymbol: "CELO",
	},
	{
		name: "Fuse",
		chainId: 122,
		gecko_id: "fuse-network-token",
		tokenSymbol: "FUSE",
	},
	{
		name: "OKTChain",
		chainId: 66,
		gecko_id: "oec-token",
		tokenSymbol: "OKT",
	},
	{
		name: "Arbitrum Nova",
		chainId: 42170,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Boba_Bnb",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Palm",
		chainId: 11297108109,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Boba_Avax",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Boba",
		chainId: 288,
		gecko_id: "boba-network",
		tokenSymbol: "BOBA",
	},
	{
		name: "Kava",
		chainId: null,
		gecko_id: "kava",
		tokenSymbol: "KAVA",
	},
	{
		name: "Harmony",
		chainId: 1666600000,
		gecko_id: "harmony",
		tokenSymbol: "ONE",
	},
	{
		name: "Moonbeam",
		chainId: 1284,
		gecko_id: "moonbeam",
		tokenSymbol: "GLMR",
	},
	{
		name: "Aurora",
		chainId: 1313161554,
		gecko_id: "aurora-near",
		tokenSymbol: "AURORA",
	},
	{
		name: "Scroll",
		chainId: 534352,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Cronos",
		chainId: 25,
		gecko_id: "crypto-com-chain",
		tokenSymbol: "CRO",
	},
	{
		name: "Velas",
		chainId: 106,
		gecko_id: "velas",
		tokenSymbol: "VLX",
	},
	{
		name: "Bittorrent",
		chainId: 199,
		gecko_id: "bittorrent",
		tokenSymbol: "BTT",
	},
	{
		name: "zkSync Era",
		chainId: 324,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Oasis",
		chainId: 42262,
		gecko_id: "oasis-network",
		tokenSymbol: "ROSE",
	},
	{
		name: "Linea",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Metis",
		chainId: 1088,
		gecko_id: "metis-token",
		tokenSymbol: "METIS",
	},
	{
		name: "Solana",
		chainId: null,
		gecko_id: "solana",
		tokenSymbol: "SOL",
	},
	{
		name: "Binance",
		chainId: 56,
		gecko_id: "binancecoin",
		tokenSymbol: "BNB",
	},
	{
		name: "IoTeX",
		chainId: 4689,
		gecko_id: "iotex",
		tokenSymbol: "IOTX",
	},
	{
		name: "Doge",
		chainId: null,
		gecko_id: "dogecoin",
		tokenSymbol: "DOGE",
	},
	{
		name: "Litecoin",
		chainId: null,
		gecko_id: "litecoin",
		tokenSymbol: "LTC",
	},
	{
		name: "KCC",
		chainId: 321,
		gecko_id: "kucoin-shares",
		tokenSymbol: "KCS",
	},
	{
		name: "Bitcoin",
		chainId: null,
		gecko_id: "bitcoin",
		tokenSymbol: "BTC",
	},
	{
		name: "Wanchain",
		chainId: 888,
		gecko_id: "wanchain",
		tokenSymbol: "WAN",
	},
	{
		name: "Terra Classic",
		chainId: null,
		gecko_id: "terra-luna",
		tokenSymbol: "LUNC",
	},
	{
		name: "OntologyEVM",
		chainId: 58,
		gecko_id: "ong",
		tokenSymbol: "ONG",
	},
	{
		name: "Ontology",
		chainId: null,
		gecko_id: "ontology",
		tokenSymbol: "ONT",
	},
	{
		name: "Polygon zkEVM",
		chainId: 1101,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Aptos",
		chainId: null,
		gecko_id: "aptos",
		tokenSymbol: "APT",
	},
	{
		name: "opBNB",
		chainId: 204,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Ronin",
		chainId: 2020,
		gecko_id: null,
		tokenSymbol: "RON",
	},
	{
		name: "Evmos",
		chainId: "9001",
		gecko_id: "evmos",
		tokenSymbol: "EVMOS",
	},
	{
		name: "Astar",
		chainId: 592,
		gecko_id: "astar",
		tokenSymbol: "ASTR",
	},
	{
		name: "Canto",
		chainId: null,
		gecko_id: "canto",
		tokenSymbol: "CANTO",
	},
	{
		name: "Conflux",
		chainId: null,
		gecko_id: "conflux-token",
		tokenSymbol: "CFX",
	},
	{
		name: "Milkomeda C1",
		chainId: 2001,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Energi",
		chainId: 39797,
		gecko_id: "energi",
		tokenSymbol: "NRG",
	},
	{
		name: "Songbird",
		chainId: 19,
		gecko_id: "songbird",
		tokenSymbol: "SGB",
	},
	{
		name: "Flare",
		chainId: null,
		gecko_id: "flare-networks",
		tokenSymbol: "FLR",
	},
	{
		name: "Hedera",
		chainId: null,
		gecko_id: "hedera-hashgraph",
		tokenSymbol: "HBAR",
	},
	{
		name: "CosmosHub",
		chainId: null,
		gecko_id: "cosmos",
		tokenSymbol: "ATOM",
	},
	{
		name: "Stafi",
		chainId: null,
		gecko_id: "stafi",
		tokenSymbol: "FIS",
	},
	{
		name: "Kusama",
		chainId: null,
		gecko_id: "kusama",
		tokenSymbol: "KSM",
	},
	{
		name: "Polkadot",
		chainId: null,
		gecko_id: "polkadot",
		tokenSymbol: "DOT",
	},
	{
		name: "Zilliqa",
		chainId: null,
		gecko_id: "zilliqa",
		tokenSymbol: "ZIL",
	},
	{
		name: "NEO",
		chainId: null,
		gecko_id: "neo",
		tokenSymbol: "NEO",
	},
	{
		name: "Klaytn",
		chainId: 8217,
		gecko_id: "klay-token",
		tokenSymbol: "KLAY",
	},
	{
		name: "Bifrost Mainnet",
		chainId: null,
		gecko_id: "bifrost",
		tokenSymbol: "BFC",
	},
	{
		name: "Secret",
		chainId: null,
		gecko_id: "secret",
		tokenSymbol: "SCRT",
	},
	{
		name: "ThunderCore",
		chainId: 108,
		gecko_id: "thunder-token",
		tokenSymbol: "TT",
	},
	{
		name: "zkSync Lite",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Rootstock",
		chainId: 30,
		gecko_id: "rootstock",
		tokenSymbol: "RBTC",
	},
	{
		name: "Cube",
		chainId: 1818,
		gecko_id: "cube-network",
		tokenSymbol: "CUBE",
	},
	{
		name: "Bitgert",
		chainId: 32520,
		gecko_id: "bitrise-token",
		tokenSymbol: "BRISE",
	},
	{
		name: "Sifchain",
		chainId: null,
		gecko_id: "sifchain",
		tokenSymbol: "EROWAN",
	},
	{
		name: "Algorand",
		chainId: null,
		gecko_id: "algorand",
		tokenSymbol: "ALGO",
	},
	{
		name: "Nuls",
		chainId: null,
		gecko_id: "nuls",
		tokenSymbol: "NULS",
	},
	{
		name: "Osmosis",
		chainId: null,
		gecko_id: "osmosis",
		tokenSymbol: "OSMO",
	},
	{
		name: "Rollux",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Mantle",
		chainId: 5000,
		gecko_id: "mantle",
		tokenSymbol: "MNT",
	},
	{
		name: "Elastos",
		chainId: 20,
		gecko_id: "elastos",
		tokenSymbol: "ELA",
	},
	{
		name: "REI",
		chainId: 47805,
		gecko_id: "rei-network",
		tokenSymbol: "REI",
	},
	{
		name: "Bitcoincash",
		chainId: null,
		gecko_id: "bitcoin-cash",
		tokenSymbol: "BCH",
	},
	{
		name: "Thorchain",
		chainId: null,
		gecko_id: "thorchain",
		tokenSymbol: "RUNE",
	},
	{
		name: "Terra2",
		chainId: null,
		gecko_id: "terra-luna-2",
		tokenSymbol: "LUNA",
	},
	{
		name: "Hoo",
		chainId: 70,
		gecko_id: "hoo-token",
		tokenSymbol: "HOO",
	},
	{
		name: "Tron",
		chainId: null,
		gecko_id: "tron",
		tokenSymbol: "TRON",
	},
	{
		name: "Icon",
		chainId: null,
		gecko_id: "icon",
		tokenSymbol: "ICX",
	},
	{
		name: "Karura",
		chainId: null,
		gecko_id: "karura",
		tokenSymbol: "KAR",
	},
	{
		name: "Tezos",
		chainId: null,
		gecko_id: "tezos",
		tokenSymbol: "XTZ",
	},
	{
		name: "EOS",
		chainId: null,
		gecko_id: "eos",
		tokenSymbol: "EOS",
	},
	{
		name: "Wax",
		chainId: null,
		gecko_id: "wax",
		tokenSymbol: "WAXP",
	},
	{
		name: "Genshiro",
		chainId: null,
		gecko_id: "genshiro",
		tokenSymbol: "GENS",
	},
	{
		name: "Near",
		chainId: null,
		gecko_id: "near",
		tokenSymbol: "NEAR",
	},
	{
		name: "Lamden",
		chainId: null,
		gecko_id: "lamden",
		tokenSymbol: "TAU",
	},
	{
		name: "Waves",
		chainId: null,
		gecko_id: "waves",
		tokenSymbol: "WAVES",
	},
	{
		name: "Shiden",
		chainId: 336,
		gecko_id: "shiden",
		tokenSymbol: "SDN",
	},
	{
		name: "CLV",
		chainId: 1024,
		gecko_id: "clover-finance",
		tokenSymbol: "CLV",
	},
	{
		name: "GoChain",
		chainId: 60,
		gecko_id: "gochain",
		tokenSymbol: "GO",
	},
	{
		name: "HPB",
		chainId: 269,
		gecko_id: "high-performance-blockchain",
		tokenSymbol: "HPB",
	},
	{
		name: "Fusion",
		chainId: 32659,
		gecko_id: "fsn",
		tokenSymbol: "FSN",
	},
	{
		name: "TomoChain",
		chainId: 88,
		gecko_id: "tomochain",
		tokenSymbol: "TOMO",
	},
	{
		name: "Persistence",
		chainId: null,
		gecko_id: "persistence",
		tokenSymbol: "XPRT",
	},
	{
		name: "EnergyWeb",
		chainId: 246,
		gecko_id: "energy-web-token",
		tokenSymbol: "EWT",
	},
	{
		name: "Radix",
		chainId: null,
		gecko_id: "radix",
		tokenSymbol: "XRD",
	},
	{
		name: "Kardia",
		chainId: 0,
		gecko_id: "kardiachain",
		tokenSymbol: "KAI",
	},
	{
		name: "Dogechain",
		chainId: null,
		gecko_id: "dogechain",
		tokenSymbol: "DG",
	},
	{
		name: "Cardano",
		chainId: null,
		gecko_id: "cardano",
		tokenSymbol: "ADA",
	},
	{
		name: "smartBCH",
		chainId: 10000,
		gecko_id: "bitcoin-cash",
		tokenSymbol: "BCH",
	},
	{
		name: "Sora",
		chainId: null,
		gecko_id: "sora",
		tokenSymbol: "XOR",
	},
	{
		name: "EthereumPoW",
		chainId: null,
		gecko_id: "ethereum-pow-iou",
		tokenSymbol: "ETHW",
	},
	{
		name: "Empire",
		chainId: null,
		gecko_id: null,
		tokenSymbol: "EMPIRE",
	},
	{
		name: "Polis",
		chainId: 333999,
		gecko_id: "polis",
		tokenSymbol: "POLIS",
	},
	{
		name: "ZYX",
		chainId: 55,
		gecko_id: "zyx",
		tokenSymbol: "ZYX",
	},
	{
		name: "Juno",
		chainId: null,
		gecko_id: "juno-network",
		tokenSymbol: "JUNO",
	},
	{
		name: "Stellar",
		chainId: null,
		gecko_id: "stellar",
		tokenSymbol: "XLM",
	},
	{
		name: "MultiversX",
		chainId: null,
		gecko_id: "elrond-erd-2",
		tokenSymbol: "EGLD",
	},
	{
		name: "Step",
		chainId: null,
		gecko_id: "stepex",
		tokenSymbol: "SPEX",
	},
	{
		name: "Mixin",
		chainId: null,
		gecko_id: "mixin",
		tokenSymbol: "XIN",
	},
	{
		name: "Everscale",
		chainId: null,
		gecko_id: "everscale",
		tokenSymbol: "EVER",
	},
	{
		name: "VeChain",
		chainId: null,
		gecko_id: "vechain",
		tokenSymbol: "VET",
	},
	{
		name: "Ubiq",
		chainId: 8,
		gecko_id: "ubiq",
		tokenSymbol: "UBQ",
	},
	{
		name: "Godwoken",
		chainId: 71394,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "GodwokenV1",
		chainId: 71402,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Callisto",
		chainId: 820,
		gecko_id: "callisto",
		tokenSymbol: "CLO",
	},
	{
		name: "EthereumClassic",
		chainId: 61,
		gecko_id: "ethereum-classic",
		tokenSymbol: "ETC",
	},
	{
		name: "Stacks",
		chainId: null,
		gecko_id: "blockstack",
		tokenSymbol: "STX",
	},
	{
		name: "CSC",
		chainId: 52,
		gecko_id: "coinex-token",
		tokenSymbol: "CET",
	},
	{
		name: "XDC",
		chainId: null,
		gecko_id: "xdce-crowd-sale",
		tokenSymbol: "XDC",
	},
	{
		name: "Echelon",
		chainId: null,
		gecko_id: "echelon",
		tokenSymbol: "ECH",
	},
	{
		name: "Ergo",
		chainId: null,
		gecko_id: "ergo",
		tokenSymbol: "ERG",
	},
	{
		name: "Nahmii",
		chainId: 5551,
		gecko_id: "nahmii",
		tokenSymbol: "NII",
	},
	{
		name: "DefiChain",
		chainId: null,
		gecko_id: "defichain",
		tokenSymbol: "DFI",
	},
	{
		name: "Heiko",
		chainId: null,
		gecko_id: null,
		tokenSymbol: "HKO",
	},
	{
		name: "Parallel",
		chainId: null,
		gecko_id: null,
		tokenSymbol: "PARA",
	},
	{
		name: "Theta",
		chainId: 361,
		gecko_id: "theta-token",
		tokenSymbol: "THETA",
	},
	{
		name: "Meter",
		chainId: 82,
		gecko_id: "meter",
		tokenSymbol: "MTRG",
	},
	{
		name: "MultiVAC",
		chainId: null,
		gecko_id: "multivac",
		tokenSymbol: "MTV",
	},
	{
		name: "RSK",
		chainId: 30,
		gecko_id: "rootstock",
		tokenSymbol: "RBTC",
	},
	{
		name: "Equilibrium",
		chainId: null,
		gecko_id: "equilibrium-token",
		tokenSymbol: "EQ",
	},
	{
		name: "Syscoin",
		chainId: 57,
		gecko_id: "syscoin",
		tokenSymbol: "SYS",
	},
	{
		name: "Proton",
		chainId: null,
		gecko_id: "proton",
		tokenSymbol: "XPR",
	},
	{
		name: "Kadena",
		chainId: null,
		gecko_id: "kadena",
		tokenSymbol: "KDA",
	},
	{
		name: "Kujira",
		chainId: null,
		gecko_id: "kujira",
		tokenSymbol: "KUJI",
	},
	{
		name: "Neutron",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Goerli",
		chainId: null,
		gecko_id: "goerli-eth",
		tokenSymbol: "GETH",
	},
	{
		name: "Vite",
		chainId: null,
		gecko_id: "vite",
		tokenSymbol: "VITE",
	},
	{
		name: "DFK",
		chainId: 53935,
		gecko_id: "defi-kingdoms",
		tokenSymbol: "JEWEL",
	},
	{
		name: "Pokt",
		chainId: null,
		gecko_id: "pocket-network",
		tokenSymbol: "POKT",
	},
	{
		name: "Milkomeda A1",
		chainId: 2002,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Findora",
		chainId: 2152,
		gecko_id: "findora",
		tokenSymbol: "FRA",
	},
	{
		name: "Hydra",
		chainId: null,
		gecko_id: "hydra",
		tokenSymbol: "HYDRA",
	},
	{
		name: "Filecoin",
		chainId: null,
		gecko_id: "filecoin",
		tokenSymbol: "FIL",
	},
	{
		name: "Bifrost",
		chainId: null,
		gecko_id: "bifrost-native-coin",
		tokenSymbol: "BNC",
	},
	{
		name: "Coti",
		chainId: null,
		gecko_id: "coti",
		tokenSymbol: "COTI",
	},
	{
		name: "Lachain",
		chainId: 225,
		gecko_id: "latoken",
		tokenSymbol: "LA",
	},
	{
		name: "REIchain",
		chainId: 55555,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Obyte",
		chainId: null,
		gecko_id: "byteball",
		tokenSymbol: "GBYTE",
	},
	{
		name: "Sui",
		chainId: null,
		gecko_id: "sui",
		tokenSymbol: "SUI",
	},
	{
		name: "SXnetwork",
		chainId: null,
		gecko_id: "sx-network",
		tokenSymbol: "SX",
	},
	{
		name: "Acala",
		chainId: null,
		gecko_id: "acala",
		tokenSymbol: "ACA",
	},
	{
		name: "Archway",
		chainId: null,
		gecko_id: "archway",
		tokenSymbol: "ARCH",
	},
	{
		name: "Sei",
		chainId: null,
		gecko_id: "sei-network",
		tokenSymbol: "SEI",
	},
	{
		name: "Injective",
		chainId: null,
		gecko_id: "injective-protocol",
		tokenSymbol: "INJ",
	},
	{
		name: "Migaloo",
		chainId: null,
		gecko_id: "white-whale",
		tokenSymbol: "WHALE",
	},
	{
		name: "Chihuahua",
		chainId: null,
		gecko_id: "chihuahua-token",
		tokenSymbol: "HUAHUA",
	},
	{
		name: "ICP",
		chainId: null,
		gecko_id: "internet-computer",
		tokenSymbol: "ICP",
	},
	{
		name: "Nova Network",
		chainId: 87,
		gecko_id: "supernova",
		tokenSymbol: "SNT",
	},
	{
		name: "Ultron",
		chainId: 1231,
		gecko_id: "ultron",
		tokenSymbol: "ULX",
	},
	{
		name: "Manta",
		chainId: 169,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Kroma",
		chainId: null,
		gecko_id: "kroma",
		tokenSymbol: "KRO",
	},
	{
		name: "WEMIX",
		chainId: null,
		gecko_id: "wemix-token",
		tokenSymbol: "WEMIX",
	},
	{
		name: "Kintsugi",
		chainId: null,
		gecko_id: "kintsugi",
		tokenSymbol: "KINT",
	},
	{
		name: "Dexit",
		chainId: null,
		gecko_id: "dexit-finance",
		tokenSymbol: "DXT",
	},
	{
		name: "CORE",
		chainId: null,
		gecko_id: "coredaoorg",
		tokenSymbol: "CORE",
	},
	{
		name: "Flow",
		chainId: null,
		gecko_id: "flow",
		tokenSymbol: "FLOW",
	},
	{
		name: "ShimmerEVM",
		chainId: 148,
		gecko_id: "shimmer",
		tokenSymbol: "SMR",
	},
	{
		name: "Loop",
		chainId: null,
		gecko_id: "loopnetwork",
		tokenSymbol: "LOOP",
	},
	{
		name: "Carbon",
		chainId: null,
		gecko_id: "switcheo",
		tokenSymbol: "SWTH",
	},
	{
		name: "Starcoin",
		chainId: null,
		gecko_id: "starcoin",
		tokenSymbol: "STC",
	},
	{
		name: "Tombchain",
		chainId: null,
		gecko_id: "tomb",
		tokenSymbol: "TOMB",
	},
	{
		name: "Vision",
		chainId: null,
		gecko_id: "vision-metaverse",
		tokenSymbol: "VS",
	},
	{
		name: "Interlay",
		chainId: null,
		gecko_id: "interlay",
		tokenSymbol: "INTR",
	},
	{
		name: "Crescent",
		chainId: null,
		gecko_id: "crescent-network",
		tokenSymbol: "CRE",
	},
	{
		name: "Pego",
		chainId: null,
		gecko_id: "pego-network-2",
		tokenSymbol: "PG",
	},
	{
		name: "FunctionX",
		chainId: null,
		gecko_id: "fx-coin",
		tokenSymbol: "FX",
	},
	{
		name: "Kekchain",
		chainId: 420420,
		gecko_id: "kekchain",
		tokenSymbol: "KEK",
	},
	{
		name: "Stride",
		chainId: null,
		gecko_id: "stride",
		tokenSymbol: "STRD",
	},
	{
		name: "MUUCHAIN",
		chainId: 20402,
		gecko_id: "muu-inu",
		tokenSymbol: "MUU",
	},
	{
		name: "TON",
		chainId: null,
		gecko_id: "the-open-network",
		tokenSymbol: "TON",
	},
	{
		name: "Starknet",
		chainId: null,
		gecko_id: "starknet",
		tokenSymbol: "STRK",
	},
	{
		name: "DSC",
		chainId: null,
		gecko_id: "decimal",
		tokenSymbol: "DEL",
	},
	{
		name: "ALV",
		chainId: null,
		gecko_id: "alvey-chain",
		tokenSymbol: "ALV",
	},
	{
		name: "Comdex",
		chainId: null,
		gecko_id: "comdex",
		tokenSymbol: "CMDX",
	},
	{
		name: "Tlchain",
		chainId: null,
		gecko_id: "tlchain",
		tokenSymbol: "TLC",
	},
	{
		name: "Zeniq",
		chainId: null,
		gecko_id: null,
		tokenSymbol: "ZENIQ",
	},
	{
		name: "Omax",
		chainId: null,
		gecko_id: "omax-token",
		tokenSymbol: "OMAX",
	},
	{
		name: "Bitindi",
		chainId: null,
		gecko_id: "bitindi-chain",
		tokenSymbol: "BNI",
	},
	{
		name: "Umee",
		chainId: null,
		gecko_id: "umee",
		tokenSymbol: "UMEE",
	},
	{
		name: "Stargaze",
		chainId: null,
		gecko_id: "stargaze",
		tokenSymbol: "STARS",
	},
	{
		name: "Libre",
		chainId: null,
		gecko_id: "libre",
		tokenSymbol: "LIBRE",
	},
	{
		name: "MAP Relay Chain",
		chainId: null,
		gecko_id: "marcopolo",
		tokenSymbol: "MAP",
	},
	{
		name: "Oraichain",
		chainId: null,
		gecko_id: "oraichain-token",
		tokenSymbol: "ORAI",
	},
	{
		name: "PulseChain",
		chainId: null,
		gecko_id: "pulsechain",
		tokenSymbol: "PLS",
	},
	{
		name: "Europa",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Darwinia",
		chainId: null,
		gecko_id: "darwinia-network-native-token",
		tokenSymbol: "RING",
	},
	{
		name: "Crab",
		chainId: 44,
		gecko_id: "darwinia-crab-network",
		tokenSymbol: "CRAB",
	},
	{
		name: "Rangers",
		chainId: null,
		gecko_id: "rangers-protocol-gas",
		tokenSymbol: "RPG",
	},
	{
		name: "Lung",
		chainId: 78887,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Bone",
		chainId: null,
		gecko_id: null,
		tokenSymbol: "BONE",
	},
	{
		name: "Shibarium",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "EOS EVM",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Quicksilver",
		chainId: null,
		gecko_id: "quicksilver",
		tokenSymbol: "QCK",
	},
	{
		name: "Oasys",
		chainId: null,
		gecko_id: "Oasys",
		tokenSymbol: "OAS",
	},
	{
		name: "ENULS",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Grove",
		chainId: null,
		gecko_id: "grove",
		tokenSymbol: "GRV",
	},
	{
		name: "XPLA",
		chainId: null,
		gecko_id: "xpla",
		tokenSymbol: "XPLA",
	},
	{
		name: "Onus",
		chainId: null,
		gecko_id: "onus",
		tokenSymbol: "ONUS",
	},
	{
		name: "Concordium",
		chainId: null,
		gecko_id: "concordium",
		tokenSymbol: "CCD",
	},
	{
		name: "Tenet",
		chainId: null,
		gecko_id: "tenet-1b000f7b-59cb-4e06-89ce-d62b32d362b9",
		tokenSymbol: "TENET",
	},
	{
		name: "Neon",
		chainId: 245022934,
		gecko_id: "neon",
		tokenSymbol: "NEON",
	},
	{
		name: "Aura Network",
		chainId: null,
		gecko_id: "aura-network",
		tokenSymbol: "AURA",
	},
	{
		name: "HydraDX",
		chainId: null,
		gecko_id: "hydradx",
		tokenSymbol: "HDX",
	},
	{
		name: "MVC",
		chainId: null,
		gecko_id: "microvisionchain",
		tokenSymbol: "SPACE",
	},
	{
		name: "RENEC",
		chainId: null,
		gecko_id: "renec",
		tokenSymbol: "RENEC",
	},
	{
		name: "Beam",
		chainId: 4337,
		gecko_id: null,
		tokenSymbol: "MC",
	},
	{
		name: "NOS",
		chainId: null,
		gecko_id: null,
		tokenSymbol: null,
	},
	{
		name: "Nolus",
		chainId: null,
		gecko_id: "nolus",
		tokenSymbol: "NLS",
	},
];
