// scripts/build-docs-index.ts
//
// Runs at `pnpm build:docs` / `pnpm prebuild`. Walks the pure
// src/mcp/catalog/tool-metadata.ts module and produces a self-contained
// embedded index in src/mcp/search-docs/embedded-index.ts. Also slurps
// any *.md files under src/mcp/search-docs/cookbook/ as prose entries.
//
// IMPORTANT: this module imports tool-metadata.ts only; that module is
// side-effect-free. Importing it must NOT trigger services/index.ts.

import { execSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { TOOL_METADATA } from "../src/mcp/catalog/tool-metadata.js";

const repoRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);
const cookbookDir = path.join(repoRoot, "src/mcp/search-docs/cookbook");
const outFile = path.join(repoRoot, "src/mcp/search-docs/embedded-index.ts");

async function loadCookbook(): Promise<
	{ id: string; title: string; content: string }[]
> {
	const entries: { id: string; title: string; content: string }[] = [];
	try {
		const files = (await fs.readdir(cookbookDir))
			.filter((f) => f.endsWith(".md"))
			.sort();
		for (const f of files) {
			const md = await fs.readFile(path.join(cookbookDir, f), "utf-8");
			const firstHeader = md.split("\n").find((l) => l.startsWith("# "));
			const title = firstHeader ? firstHeader.replace(/^#\s+/, "") : f;
			entries.push({ id: `cookbook:${f}`, title, content: md });
		}
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
	return entries;
}

async function main() {
	const cookbook = await loadCookbook();
	const methodEntries = TOOL_METADATA.map((m) => ({
		kind: "method" as const,
		name: m.name,
		qualified: m.qualified,
		description: m.description,
		params: z.toJSONSchema(m.parameters),
		exampleCall: m.exampleCall,
	}));

	const entries = [
		...methodEntries,
		...cookbook.map((c) => ({ kind: "prose" as const, ...c })),
	];

	/**
	 * JSON.stringify produces double-quoted keys and no trailing commas;
	 * Biome's `format --write` post-pass (below) unquotes identifier keys
	 * (`quoteProperties: "asNeeded"` default) and adds trailing commas
	 * (`trailingCommas: "all"` default), producing idiomatic TypeScript.
	 */
	const out = `// AUTO-GENERATED by scripts/build-docs-index.ts. Do not edit by hand.
// Re-run \`pnpm run build:docs\` to regenerate.

export type MethodEntry = {
	kind: "method";
	name: string;
	qualified: string;
	description: string;
	params: unknown;
	exampleCall: string;
};

export type ProseEntry = {
	kind: "prose";
	id: string;
	title: string;
	content: string;
};

export type IndexEntry = MethodEntry | ProseEntry;

export const ENTRIES: IndexEntry[] = ${JSON.stringify(entries, null, "\t")};
`;

	await fs.mkdir(path.dirname(outFile), { recursive: true });
	await fs.writeFile(outFile, out);
	// Auto-format with Biome so the committed file always passes `pnpm lint`.
	execSync(`pnpm exec biome format --write ${outFile}`, { stdio: "inherit" });
	console.log(`Wrote ${entries.length} entries to ${outFile}`);
}

void main();
