// scripts/build-instructions.ts
//
// Reads src/mcp/instructions/instructions.md and writes
// src/mcp/instructions/instructions.generated.ts with the content embedded
// as an escaped template literal. The escaping reverses at runtime — the
// exported INSTRUCTIONS value is byte-identical to the markdown source.
//
// We use a template literal (not JSON.stringify) so the committed file
// preserves the markdown's line structure and stays human-readable.

import { execSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);
const srcFile = path.join(repoRoot, "src/mcp/instructions/instructions.md");
const outFile = path.join(
	repoRoot,
	"src/mcp/instructions/instructions.generated.ts",
);

/**
 * Escape the three characters that have meaning inside a template literal,
 * in this order: backslash first (so the later escapes' backslashes aren't
 * doubled), then backtick, then `${` (template interpolation start). The
 * runtime evaluator reverses all three when parsing the literal — net
 * effect: the runtime string equals the input bytes.
 */
function escapeForTemplate(s: string): string {
	return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function main() {
	let markdown: string;
	try {
		markdown = await fs.readFile(srcFile, "utf-8");
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") {
			console.error(
				`instructions.md not found at ${srcFile}; cannot generate instructions.generated.ts`,
			);
			process.exit(1);
		}
		throw err;
	}
	const out = `// AUTO-GENERATED by scripts/build-instructions.ts. Do not edit by hand.
// Re-run \`pnpm run build:instructions\` to regenerate.

export const INSTRUCTIONS = \`${escapeForTemplate(markdown)}\`;
`;
	await fs.mkdir(path.dirname(outFile), { recursive: true });
	await fs.writeFile(outFile, out);
	// Auto-format with Biome so the committed file always passes `pnpm lint`.
	execSync(`pnpm exec biome format --write ${outFile}`, { stdio: "inherit" });
	console.log(`Wrote instructions (${markdown.length} chars) to ${outFile}`);
}

void main();
