// AUTO-GENERATED by scripts/build-instructions.ts. Do not edit by hand.
// Re-run `pnpm run build:instructions` to regenerate.

export const INSTRUCTIONS = `# DefiLlama MCP — agent instructions

This server exposes DefiLlama DeFi data through a Code Mode surface. Use \`execute\`
to run sandboxed JavaScript against the pre-wired \`defillama.*\` client and project
the result, and \`search_docs\` to find endpoints and recipes.

(Full operational guide — endpoint groups, the chain name vs. coins-slug convention,
the \`chain:address\` price format, IQ Gateway behavior, and sandbox limits — is added
in a later phase.)
`;
